### ISSUE TITLE
Error when running with current webpack config.

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/plugins#1]
When running with current github config i face this error:

![image](https://cloud.githubusercontent.com/assets/7657429/18762747/d1cac8d8-8112-11e6-8337-c446dcd28b33.png)

Error points to [this line](https://github.com/WhitestormJS/plugins/blob/master/webpack.config.babel.js#L84).

**Comment by preco21** [comment]
This seems like braking change of `webpack`.

Related issue: https://github.com/angular/angular-cli/issues/2234

Migration guide: https://github.com/webpack/webpack.js.org/blob/develop/content/how-to/upgrade-from-webpack-1.md#resolveextensions

**Comment by preco21** [comment]
@sasha240100 What is your `webpack` version?

**Comment by sasha240100** [comment]
@preco21 it says that I can't use " " (empty), only like ".js"
I fixed that typo before, it seems you returned it back

**Comment by preco21** [comment]
@sasha240100 Yup, that was braking changes, but didn't know. So I had reverted changes. My bad. :wink:

**Comment by preco21** [comment]
Closed via https://github.com/WhitestormJS/plugins/commit/d37fb888aaedbd1cbc469d39622badf152dc56af
